--
-- PostgreSQL database dump
--

-- Dumped from database version 12.2
-- Dumped by pg_dump version 12.2

-- Started on 2020-05-16 17:33:29

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16642)
-- Name: ban_banknote; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ban_banknote (
    ban_id integer NOT NULL,
    ban_ser_id integer NOT NULL,
    ban_cus_id integer NOT NULL,
    ban_face_value numeric NOT NULL,
    ban_material text,
    ban_obverse_desc text,
    ban_reverse_desc text,
    ban_size_width integer,
    ban_size_height integer,
    ban_description text
);


ALTER TABLE public.ban_banknote OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16640)
-- Name: ban_banknote_ban_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ban_banknote ALTER COLUMN ban_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ban_banknote_ban_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 100
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16711)
-- Name: bit_item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bit_item (
    bit_id integer NOT NULL,
    bit_usr_id integer NOT NULL,
    bit_bva_id integer NOT NULL,
    bit_quantity integer NOT NULL,
    bit_gra_grade text NOT NULL,
    bit_price real NOT NULL,
    bit_seller text,
    bit_purchase_date text,
    bit_description text
);


ALTER TABLE public.bit_item OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16709)
-- Name: bit_item_bit_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bit_item ALTER COLUMN bit_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bit_item_bit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 100
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16662)
-- Name: bta_banknote_tag; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bta_banknote_tag (
    bta_id integer NOT NULL,
    bta_ban_id integer NOT NULL,
    bta_side text DEFAULT 'O'::text NOT NULL,
    bta_tag text NOT NULL
);


ALTER TABLE public.bta_banknote_tag OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16660)
-- Name: bta_banknote_tag_bta_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bta_banknote_tag ALTER COLUMN bta_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bta_banknote_tag_bta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 100
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16678)
-- Name: bva_variant; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bva_variant (
    bva_id integer NOT NULL,
    bva_ban_id integer NOT NULL,
    bva_issue_year integer NOT NULL,
    bva_printed_date text,
    bva_cat_id text NOT NULL,
    bva_overstamped_id integer,
    bva_printer text,
    bva_signature text,
    bva_signature_ext text,
    bva_watermark text,
    bva_security_thread text,
    bva_added_security text,
    bva_is_specimen integer DEFAULT 0 NOT NULL,
    bva_is_commemorative integer DEFAULT 0 NOT NULL,
    bva_is_numis_product integer DEFAULT 0 NOT NULL,
    bva_is_replacement integer DEFAULT 0 NOT NULL,
    bva_is_error integer DEFAULT 0 NOT NULL,
    bva_description text
);


ALTER TABLE public.bva_variant OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16676)
-- Name: bva_variant_bva_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bva_variant ALTER COLUMN bva_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bva_variant_bva_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 100
    CACHE 1
);


--
-- TOC entry 203 (class 1259 OID 16532)
-- Name: con_continent; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.con_continent (
    con_id integer NOT NULL,
    con_name text NOT NULL,
    con_order integer
);


ALTER TABLE public.con_continent OWNER TO postgres;

--
-- TOC entry 202 (class 1259 OID 16530)
-- Name: con_continent_con_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.con_continent ALTER COLUMN con_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.con_continent_con_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 100
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 16572)
-- Name: cur_currency; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cur_currency (
    cur_id integer NOT NULL,
    cur_symbol text,
    cur_name text NOT NULL,
    cur_full_name text,
    cur_start text,
    cur_end text,
    cur_successor integer,
    cur_replacement_rate real,
    cur_description text
);


ALTER TABLE public.cur_currency OWNER TO postgres;

--
-- TOC entry 208 (class 1259 OID 16570)
-- Name: cur_currency_cur_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cur_currency ALTER COLUMN cur_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cur_currency_cur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 100
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 16582)
-- Name: cus_currency_unit; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cus_currency_unit (
    cus_id integer NOT NULL,
    cus_cur_id integer,
    cus_value real NOT NULL,
    cus_name text NOT NULL,
    cus_abbreviation text
);


ALTER TABLE public.cus_currency_unit OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 16580)
-- Name: cus_currency_unit_cus_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cus_currency_unit ALTER COLUMN cus_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cus_currency_unit_cus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 100
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16701)
-- Name: gra_grade; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.gra_grade (
    gra_value integer NOT NULL,
    gra_grade text NOT NULL,
    gra_name text NOT NULL,
    gra_description text
);


ALTER TABLE public.gra_grade OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16627)
-- Name: ser_series; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ser_series (
    ser_id integer NOT NULL,
    ser_cur_id integer NOT NULL,
    ser_name text NOT NULL,
    ser_start integer NOT NULL,
    ser_end integer,
    ser_issuer text,
    ser_law_date text,
    ser_description text
);


ALTER TABLE public.ser_series OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16625)
-- Name: ser_series_ser_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ser_series ALTER COLUMN ser_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ser_series_ser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 100
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 16595)
-- Name: tec_territory_currency; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tec_territory_currency (
    tec_ter_id integer NOT NULL,
    tec_cur_id integer NOT NULL,
    tec_iso3 text,
    tec_cur_type text NOT NULL,
    tec_start text,
    tec_end text
);


ALTER TABLE public.tec_territory_currency OWNER TO postgres;

--
-- TOC entry 207 (class 1259 OID 16552)
-- Name: ter_territory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ter_territory (
    ter_id integer NOT NULL,
    ter_con_id integer NOT NULL,
    ter_tty_id integer NOT NULL,
    ter_iso2 text,
    ter_iso3 text,
    ter_name text NOT NULL,
    ter_official_name text,
    ter_start integer NOT NULL,
    ter_end integer,
    ter_parent_country_id integer,
    ter_successor_id text,
    ter_description text
);


ALTER TABLE public.ter_territory OWNER TO postgres;

--
-- TOC entry 206 (class 1259 OID 16550)
-- Name: ter_territory_ter_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ter_territory ALTER COLUMN ter_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ter_territory_ter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 10000
    CACHE 1
);


--
-- TOC entry 205 (class 1259 OID 16542)
-- Name: tty_territory_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tty_territory_type (
    tty_id integer NOT NULL,
    tty_name text NOT NULL,
    tty_abbr text,
    tty_desc text,
    tty_order integer
);


ALTER TABLE public.tty_territory_type OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 16540)
-- Name: tty_territory_type_tty_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tty_territory_type ALTER COLUMN tty_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tty_territory_type_tty_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 100
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 16615)
-- Name: usr_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usr_user (
    usr_id integer NOT NULL,
    usr_name text NOT NULL
);


ALTER TABLE public.usr_user OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 16613)
-- Name: usr_user_usr_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usr_user ALTER COLUMN usr_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usr_user_usr_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 100
    CACHE 1
);


--
-- TOC entry 2793 (class 2606 OID 16649)
-- Name: ban_banknote ban_banknote_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ban_banknote
    ADD CONSTRAINT ban_banknote_pkey PRIMARY KEY (ban_id);


--
-- TOC entry 2801 (class 2606 OID 16718)
-- Name: bit_item bit_item_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bit_item
    ADD CONSTRAINT bit_item_pkey PRIMARY KEY (bit_id);


--
-- TOC entry 2795 (class 2606 OID 16670)
-- Name: bta_banknote_tag bta_banknote_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bta_banknote_tag
    ADD CONSTRAINT bta_banknote_tag_pkey PRIMARY KEY (bta_id);


--
-- TOC entry 2797 (class 2606 OID 16690)
-- Name: bva_variant bva_variant_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bva_variant
    ADD CONSTRAINT bva_variant_pkey PRIMARY KEY (bva_id);


--
-- TOC entry 2775 (class 2606 OID 16539)
-- Name: con_continent con_continent_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.con_continent
    ADD CONSTRAINT con_continent_pkey PRIMARY KEY (con_id);


--
-- TOC entry 2781 (class 2606 OID 16579)
-- Name: cur_currency cur_currency_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cur_currency
    ADD CONSTRAINT cur_currency_pkey PRIMARY KEY (cur_id);


--
-- TOC entry 2783 (class 2606 OID 16589)
-- Name: cus_currency_unit cus_currency_unit_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cus_currency_unit
    ADD CONSTRAINT cus_currency_unit_pkey PRIMARY KEY (cus_id);


--
-- TOC entry 2799 (class 2606 OID 16708)
-- Name: gra_grade gra_grade_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gra_grade
    ADD CONSTRAINT gra_grade_pkey PRIMARY KEY (gra_value);


--
-- TOC entry 2791 (class 2606 OID 16634)
-- Name: ser_series ser_series_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ser_series
    ADD CONSTRAINT ser_series_pkey PRIMARY KEY (ser_id);


--
-- TOC entry 2785 (class 2606 OID 16602)
-- Name: tec_territory_currency tec_territory_currency_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tec_territory_currency
    ADD CONSTRAINT tec_territory_currency_pkey PRIMARY KEY (tec_ter_id, tec_cur_id);


--
-- TOC entry 2779 (class 2606 OID 16559)
-- Name: ter_territory ter_territory_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ter_territory
    ADD CONSTRAINT ter_territory_pkey PRIMARY KEY (ter_id);


--
-- TOC entry 2777 (class 2606 OID 16549)
-- Name: tty_territory_type tty_territory_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tty_territory_type
    ADD CONSTRAINT tty_territory_type_pkey PRIMARY KEY (tty_id);


--
-- TOC entry 2787 (class 2606 OID 16622)
-- Name: usr_user usr_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usr_user
    ADD CONSTRAINT usr_user_pkey PRIMARY KEY (usr_id);


--
-- TOC entry 2789 (class 2606 OID 16624)
-- Name: usr_user usr_user_usr_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usr_user
    ADD CONSTRAINT usr_user_usr_name_key UNIQUE (usr_name);


--
-- TOC entry 2802 (class 2606 OID 16560)
-- Name: ter_territory FK_CON_ID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ter_territory
    ADD CONSTRAINT "FK_CON_ID" FOREIGN KEY (ter_con_id) REFERENCES public.con_continent(con_id);


--
-- TOC entry 2803 (class 2606 OID 16565)
-- Name: ter_territory FK_TTY_ID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ter_territory
    ADD CONSTRAINT "FK_TTY_ID" FOREIGN KEY (ter_tty_id) REFERENCES public.tty_territory_type(tty_id);


--
-- TOC entry 2809 (class 2606 OID 16655)
-- Name: ban_banknote ban_banknote_ban_cus_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ban_banknote
    ADD CONSTRAINT ban_banknote_ban_cus_id_fkey FOREIGN KEY (ban_cus_id) REFERENCES public.cus_currency_unit(cus_id);


--
-- TOC entry 2808 (class 2606 OID 16650)
-- Name: ban_banknote ban_banknote_ban_ser_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ban_banknote
    ADD CONSTRAINT ban_banknote_ban_ser_id_fkey FOREIGN KEY (ban_ser_id) REFERENCES public.ser_series(ser_id);


--
-- TOC entry 2813 (class 2606 OID 16719)
-- Name: bit_item bit_item_bit_bva_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bit_item
    ADD CONSTRAINT bit_item_bit_bva_id_fkey FOREIGN KEY (bit_bva_id) REFERENCES public.bva_variant(bva_id);


--
-- TOC entry 2810 (class 2606 OID 16671)
-- Name: bta_banknote_tag bta_banknote_tag_bta_ban_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bta_banknote_tag
    ADD CONSTRAINT bta_banknote_tag_bta_ban_id_fkey FOREIGN KEY (bta_ban_id) REFERENCES public.ban_banknote(ban_id);


--
-- TOC entry 2811 (class 2606 OID 16691)
-- Name: bva_variant bva_variant_bva_ban_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bva_variant
    ADD CONSTRAINT bva_variant_bva_ban_id_fkey FOREIGN KEY (bva_ban_id) REFERENCES public.ban_banknote(ban_id);


--
-- TOC entry 2812 (class 2606 OID 16696)
-- Name: bva_variant bva_variant_bva_overstamped_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bva_variant
    ADD CONSTRAINT bva_variant_bva_overstamped_id_fkey FOREIGN KEY (bva_overstamped_id) REFERENCES public.bva_variant(bva_id);


--
-- TOC entry 2804 (class 2606 OID 16590)
-- Name: cus_currency_unit cus_currency_unit_cus_cur_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cus_currency_unit
    ADD CONSTRAINT cus_currency_unit_cus_cur_id_fkey FOREIGN KEY (cus_cur_id) REFERENCES public.cur_currency(cur_id);


--
-- TOC entry 2807 (class 2606 OID 16635)
-- Name: ser_series ser_series_ser_cur_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ser_series
    ADD CONSTRAINT ser_series_ser_cur_id_fkey FOREIGN KEY (ser_cur_id) REFERENCES public.cur_currency(cur_id);


--
-- TOC entry 2805 (class 2606 OID 16603)
-- Name: tec_territory_currency tec_territory_currency_tec_cur_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tec_territory_currency
    ADD CONSTRAINT tec_territory_currency_tec_cur_id_fkey FOREIGN KEY (tec_cur_id) REFERENCES public.cur_currency(cur_id);


--
-- TOC entry 2806 (class 2606 OID 16608)
-- Name: tec_territory_currency tec_territory_currency_tec_ter_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tec_territory_currency
    ADD CONSTRAINT tec_territory_currency_tec_ter_id_fkey FOREIGN KEY (tec_ter_id) REFERENCES public.ter_territory(ter_id);


--
-- TOC entry 2945 (class 0 OID 0)
-- Dependencies: 218
-- Name: TABLE ban_banknote; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ban_banknote TO "AppAPI";


--
-- TOC entry 2946 (class 0 OID 0)
-- Dependencies: 225
-- Name: TABLE bit_item; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.bit_item TO "AppAPI";


--
-- TOC entry 2947 (class 0 OID 0)
-- Dependencies: 220
-- Name: TABLE bta_banknote_tag; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.bta_banknote_tag TO "AppAPI";


--
-- TOC entry 2948 (class 0 OID 0)
-- Dependencies: 222
-- Name: TABLE bva_variant; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.bva_variant TO "AppAPI";


--
-- TOC entry 2949 (class 0 OID 0)
-- Dependencies: 203
-- Name: TABLE con_continent; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.con_continent TO "AppAPI";


--
-- TOC entry 2950 (class 0 OID 0)
-- Dependencies: 209
-- Name: TABLE cur_currency; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.cur_currency TO "AppAPI";


--
-- TOC entry 2951 (class 0 OID 0)
-- Dependencies: 211
-- Name: TABLE cus_currency_unit; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.cus_currency_unit TO "AppAPI";


--
-- TOC entry 2952 (class 0 OID 0)
-- Dependencies: 223
-- Name: TABLE gra_grade; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.gra_grade TO "AppAPI";


--
-- TOC entry 2953 (class 0 OID 0)
-- Dependencies: 216
-- Name: TABLE ser_series; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ser_series TO "AppAPI";


--
-- TOC entry 2954 (class 0 OID 0)
-- Dependencies: 212
-- Name: TABLE tec_territory_currency; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.tec_territory_currency TO "AppAPI";


--
-- TOC entry 2955 (class 0 OID 0)
-- Dependencies: 207
-- Name: TABLE ter_territory; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ter_territory TO "AppAPI";


--
-- TOC entry 2956 (class 0 OID 0)
-- Dependencies: 205
-- Name: TABLE tty_territory_type; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.tty_territory_type TO "AppAPI";


--
-- TOC entry 2957 (class 0 OID 0)
-- Dependencies: 214
-- Name: TABLE usr_user; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.usr_user TO "AppAPI";


-- Completed on 2020-05-16 17:33:29

--
-- PostgreSQL database dump complete
--

